version: '3'
services:
  web:
    build:
      context: . #where we want all the files and folders to be pulled from
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # do not map nodule modules inside the container
      - .:/app
